version: '3.8'

services:
  postgres:
    container_name: biometric-service-postgres
    image: postgres:13
    domainname: postgres

    environment:
      POSTGRES_DB: biometric_service_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"


  flyway:
    container_name: biometric-service-flyway
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres:5432/biometric_service_postgres?verifyServerCertificate=false&useSSL=true -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - postgres

  redis:
    container_name: biometric-service-redis
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"